[package]
name = "gdelt-sqlx"
description= "High-level sqlx bindings for the GDELT 2.0 dataset"
version = "0.1.0"
authors = ["Owez <root@ogriffiths.com>"]
readme = "README.md"
license = "MIT"
edition = "2018"
